language: cpp

#sudo: false

cache:
        - ccache
        - apt

before_install: sudo ./travis-setup.sh

script: 
        - export PATH="${PWD}/cmake/root/bin:${PATH}"
        - export CC=gcc-4.8
        - export CXX=g++-4.8
        - ./build-llvm-with-safestack.sh -j2
